version: '3.8'
services:
  bot:
    image: ghcr.io/quocnguyen192/finance_tele_bot:latest
    env_file: .env
    ports:
      - "9300:9300"
    
    volumes:
      - ./service_account.json:/app/service_account.json:ro
